routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// view route
Route::view('/', 'welcome');
// resource controller with repository design pattern
Route::resource('codes', 'CodeController')->only(['index', 'create', 'store']);
// single action controller
Route::post('submit', 'SubmitController')->name('submit');

Route::get('winners', 'WinnerController@index')->name('winners.index');

app/Models/Code.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Code extends Model
{
    use HasFactory, SoftDeletes;

    protected $fillable = [
        'name' , 'code' , 'limit' , 'used'
    ];
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Models/Winner.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Winner extends Model
{
    use HasFactory, SoftDeletes;

    protected $fillable = ['mobile', 'code_id'];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function code()
    {
        return $this->belongsTo('App\Models\Code');
    }
}

app/Http/Controllers/CodeController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CodeRequest;
use Illuminate\Http\RedirectResponse;
use Illuminate\Contracts\View\Factory;
use App\Repositories\Eloquent\CodeRepository;
use App\Repositories\Interfaces\CodeRepositoryInterface;

class CodeController extends Controller
{
    /**
     * @var CodeRepositoryInterface|CodeRepository
     */
    private $codeRepository;

    /**
     * CodeController constructor.
     * @param CodeRepositoryInterface $codeRepository
     */
    public function __construct(CodeRepositoryInterface $codeRepository)
    {
        $this->codeRepository = $codeRepository;
    }

    /**
     * Display a listing of the resource.
     *
     * @return Factory
     */
    public function index()
    {
        $codes = $this->codeRepository
            ->paginated();

        return view('codes.index' , [
            'codes' => $codes
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Factory
     */
    public function create()
    {
        return view('codes.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param CodeRequest $request
     * @return RedirectResponse
     */
    public function store(CodeRequest $request)
    {
        $this->codeRepository->store($request);

        return redirect()->route('codes.index');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/SubmitController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\SubmitRequest;
use App\Services\Submitter;
use \Illuminate\Http\RedirectResponse;

class SubmitController extends Controller
{
    /**
     * @var Submitter
     */
    private $submitter;

    /**
     * SubmitController constructor.
     * @param Submitter $submitter
     */
    public function __construct(Submitter $submitter)
    {
        $this->submitter = $submitter;
    }

    /**
     * @param SubmitRequest $request
     * @return RedirectResponse
     */
    public function __invoke(SubmitRequest $request)
    {
        $this->submitter = $this->submitter->setRequest($request);

        if ($this->submitter->attempt()) {
            $request->session()->flash('alert-success', 'YOU WON !');
            return redirect()->back();
        }

        $request->session()->flash('alert-danger', 'too slow !');
        return redirect()->back();
    }
}

app/Http/Controllers/WinnerController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\IsWinnerRequest;
use App\Repositories\Interfaces\WinnerRepositoryInterface;
use Illuminate\Contracts\View\Factory as ViewFactory;

class WinnerController extends Controller
{
    /**
     * @var WinnerRepositoryInterface
     */
    private $winnerRepository;

    /**
     * WinnerController constructor.
     * @param WinnerRepositoryInterface $winnerRepository
     */
    public function __construct(WinnerRepositoryInterface $winnerRepository)
    {
        $this->winnerRepository = $winnerRepository;
    }

    /**
     * @return ViewFactory
     */
    public function index()
    {
        $winners = $this->winnerRepository->paginated();

        return view('winners.index' ,[
            'winners' => $winners
        ]);
    }

    public function isWinner(IsWinnerRequest $request)
    {
        $is_winner = $this->winnerRepository->isWinner($request);

        return response()->json([
            'is_winner' => $is_winner
        ]);
    }
}

resources/views/codes/create.blade.php
@extends('layouts.master')

@section('content')

    <div class="row">
        <div class="col-6">
            <form action="{{ route('codes.store') }}" method="post">
                @csrf

                @include('codes.form')
            </form>
        </div>
    </div>

@endsection

resources/views/codes/form.blade.php
<div class="form-group">
    <label for="name">Name : </label>
    <input type="text" name="name" class="form-control" id="name" aria-describedby="nameHelp" placeholder="Enter name">
</div>

<div class="form-group">
    <label for="code">Code : </label>
    <input type="text" class="form-control" name="code" id="code" placeholder="enter the code">
</div>

<div class="form-group">
    <label for="limit">Limit : </label>
    <input type="number" class="form-control" id="limit" name="limit" placeholder="enter the limit">
</div>

<button type="submit" class="btn btn-primary mt-5">Submit</button>

resources/views/codes/index.blade.php
@extends('layouts.master')


@section('content')

    <div class="row mb-5">
        <div class="col-3">
            <h1>Codes</h1>
        </div>
        <div class="col-3">
            <a href="{{ route('codes.create') }}" class="btn btn-success w-100">Create code</a>
        </div>
        <div class="col-6">
            {!! $codes->links() !!}
        </div>

    </div>
    <hr>
    <div class="row">
        <div class="col-12">
            <table class="table">
                <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">name</th>
                    <th scope="col">Code</th>
                    <th scope="col">Limit</th>
                </tr>
                </thead>
                <tbody>
                @foreach($codes as $code)
                    <tr>
                        <th scope="row">{{ $loop->iteration }}</th>
                        <td>{{ $code->name }}</td>
                        <td>{{ $code->code }}</td>
                        <td>{{ $code->limit }}</td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>

@endsection

resources/views/layouts/master.blade.php
@extends('layouts.skeleton')

@section('master')

    @include('partials.messages')

    @yield('content')

@endsection

resources/views/layouts/skeleton.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.79.0">
    <title>Signin Template · Bootstrap v5.0</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/sign-in/">


    <!-- Bootstrap core CSS -->
    <link href="https://getbootstrap.com/docs/5.0/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Favicons -->
    <link rel="apple-touch-icon" href="https://getbootstrap.com/docs/5.0/assets/img/favicons/apple-touch-icon.png"
          sizes="180x180">
    <link rel="icon" href="https://getbootstrap.com/docs/5.0/assets/img/favicons/favicon-32x32.png" sizes="32x32"
          type="image/png">
    <link rel="icon" href="https://getbootstrap.com/docs/5.0/assets/img/favicons/favicon-16x16.png" sizes="16x16"
          type="image/png">
    <link rel="manifest" href="https://getbootstrap.com/docs/5.0/assets/img/favicons/manifest.json">
    <link rel="mask-icon" href="https://getbootstrap.com/docs/5.0/assets/img/favicons/safari-pinned-tab.svg"
          color="#7952b3">
    <link rel="icon" href="https://getbootstrap.com/docs/5.0/assets/img/favicons/favicon.ico">
    <meta name="theme-color" content="#7952b3">
    <link href='http://www.fontonline.ir/css/BYekan.css' rel='stylesheet' type='text/css'>


    @stack('styles')
</head>
<body dir="rtl">

    <div class="container mt-5" dir="ltr">
        @yield('master')


    </div>
    @stack('scripts')
</body>
</html>

resources/views/partials/messages.blade.php
@foreach (['danger', 'warning', 'success', 'info'] as $msg)
    @if(Session::has('alert-'.$msg))
        <div class="alert alert-{{ $msg }} mt-4" role="alert">
            {{ Session::get('alert-'.$msg) }}
        </div>
    @endif
@endforeach

@if ($errors->any())
    <div class="alert alert-danger mt-4" role="alert">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

resources/views/winners/index.blade.php
@extends('layouts.master')

@section('content')

    <div class="row">
        <div class="col-2">
            <h1>Winners</h1>
        </div>
        <div class="col-10">
            {!! $winners->links() !!}
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-12">
            <table class="table">
                <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Mobile</th>
                    <th scope="col">Created At</th>
                </tr>
                </thead>
                <tbody>
                @foreach($winners as $winner)
                    <tr>
                        <th scope="row">{{ $loop->iteration }}</th>
                        <td>{{ $winner->mobile }}</td>
                        <td>{{ $winner->created_at->diffForHumans() }}</td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>

@endsection